import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { IoCallOutline } from "react-icons/io5";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Future Wings Academy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Tawk.to Script */}
        <Script
          id="tawk-to"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),
                    s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/698986c9c060e01c37488e01/1jh0jd1la';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />

        <Navbar />
        {children}

        {/* Floating Call Button */}
        <a href="tel:8679234969" className="z-50">
          <div className="fixed bottom-6 md:bottom-4 left-4 md:w-16 w-14 md:h-16 h-14 bg-blue-600 flex justify-center items-center rounded-full">
            <IoCallOutline className="md:w-8 w-7 md:h-8 h-7 text-white" />
          </div>
        </a>

        <Footer />
      </body>
    </html>
  );
}
